server:
  port: 8081

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/credit_watch?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root